name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: 패키지 설치
        run: yarn install --frozen-lockfile
      - name: 코어 (디자인시스템) 빌드
        run: yarn build:core
      - name: 블로그 빌드
        run: yarn build:blog
      - name: git config 설정
        run: |
          git config --global user.email "sun@dataportal.kr"
          git config --global user.name "Taeyang Jin (Theo)"
      - name: heli-os.github.io 배포
        run: cd packages/blog && node scripts/deploy.js ${{ secrets.TOKEN }}
